# Generated by Django 4.2.29 on 2026-07-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('mpesa', 'M-Pesa'), ('stripe', 'Stripe'), ('bank', 'Bank')], max_length=20)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('shortcode', models.CharField(blank=True, max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('account_reference_format', models.CharField(blank=True, max_length=100)),
                ('callback_url', models.URLField(blank=True)),
                ('validation_url', models.URLField(blank=True)),
                ('confirmation_url', models.URLField(blank=True)),
                ('consumer_key', models.CharField(blank=True, max_length=200)),
                ('consumer_secret', models.CharField(blank=True, max_length=200)),
                ('passkey', models.CharField(blank=True, max_length=200)),
                ('transaction_timeout', models.IntegerField(default=30)),
                ('stk_push_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Payment Channel',
                'verbose_name_plural': 'Payment Channels',
            },
        ),
    ]
